import accentureLogo from '../assets/company-logos/accenture.png';
import adobeLogo from '../assets/company-logos/adobe.png';
import amazonLogo from '../assets/company-logos/amazon.png';
import apolloLogo from '../assets/company-logos/apollo-hospitals.png';
import appleLogo from '../assets/company-logos/apple.png';
import ciscoLogo from '../assets/company-logos/cisco.png';
import concentrixLogo from '../assets/company-logos/concentrix.png';
import courseraLogo from '../assets/company-logos/coursera.png';
import deloitteLogo from '../assets/company-logos/deloitte.png';
import eyLogo from '../assets/company-logos/ey.png';
import goldmanSachsLogo from '../assets/company-logos/goldman-sachs.png';
import googleLogo from '../assets/company-logos/google.png';
import hclLogo from '../assets/company-logos/hcl.png';
import hdfcLogo from '../assets/company-logos/hdfc.png';
import hulLogo from '../assets/company-logos/hindustan-unilever.png';
import hsbcLogo from '../assets/company-logos/hsbc.png';
import ibmLogo from '../assets/company-logos/ibm.png';
import infosysLogo from '../assets/company-logos/infosys.png';
import jioLogo from '../assets/company-logos/reliance-jio-platforms.png';
import jpmorganLogo from '../assets/company-logos/jpmorgan.png';
import kpmgLogo from '../assets/company-logos/kpmg.png';
import manipalLogo from '../assets/company-logos/manipal-hospitals.png';
import microsoftLogo from '../assets/company-logos/microsoft.png';
import nvidiaLogo from '../assets/company-logos/nvidia.png';
import pwcLogo from '../assets/company-logos/pwc.png';
import razorpayLogo from '../assets/company-logos/razorpay.png';
import sunPharmaLogo from '../assets/company-logos/sun-pharma.png';
import tataMotorsLogo from '../assets/company-logos/tata-motors.png';
import tcsLogo from '../assets/company-logos/tcs.png';
import walmartLogo from '../assets/company-logos/walmart-global-tech.png';
import zscalerLogo from '../assets/company-logos/zscaler.png';
import delhiveryLogo from '../assets/company-logos/delhivery.png';

export interface CompanyConfig {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  industry: string;
  industrySlug: string;
  domains: string[];
  description: string;
  website: string;
  careerPage: string;
  aspectHint?: 'wide' | 'square' | 'horizontal';
  fallbackText: string;
}

// Map of canonical company configurations
const BASE_COMPANY_CONFIGS: Record<string, CompanyConfig> = {
  // EXISTING COMPANIES (PROTECTED & UNTOUCHED)
  google: {
    id: 'google',
    slug: 'google',
    name: 'Google',
    logo: googleLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Software Engineering', 'AI / ML', 'Cloud & DevOps', 'Cybersecurity'],
    description: 'Multinational technology company specializing in internet services, search, AI, cloud computing, and hardware.',
    website: 'https://www.google.com',
    careerPage: 'https://careers.google.com',
    aspectHint: 'square',
    fallbackText: 'G',
  },
  microsoft: {
    id: 'microsoft',
    slug: 'microsoft',
    name: 'Microsoft',
    logo: microsoftLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Software Engineering', 'Cloud & DevOps', 'AI / ML', 'Cybersecurity'],
    description: 'Global leader in software, operating systems, cloud computing (Azure), Xbox gaming, and AI development.',
    website: 'https://www.microsoft.com',
    careerPage: 'https://careers.microsoft.com',
    aspectHint: 'wide',
    fallbackText: 'MSFT',
  },
  amazon: {
    id: 'amazon',
    slug: 'amazon',
    name: 'Amazon',
    logo: amazonLogo,
    industry: 'E-Commerce, Retail & FMCG',
    industrySlug: 'retail',
    domains: ['E-Commerce Platforms', 'Cloud & DevOps', 'Supply Chain & Logistics', 'AI / ML'],
    description: 'E-commerce and cloud computing giant driving AWS cloud, Prime streaming, and global logistics.',
    website: 'https://www.amazon.com',
    careerPage: 'https://www.amazon.jobs',
    aspectHint: 'horizontal',
    fallbackText: 'AMZN',
  },
  adobe: {
    id: 'adobe',
    slug: 'adobe',
    name: 'Adobe',
    logo: adobeLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Software Engineering', 'UI/UX Design', 'Digital Media', 'Cloud & DevOps'],
    description: 'Creative software pioneer providing Photoshop, Illustrator, Acrobat, and enterprise experience platforms.',
    website: 'https://www.adobe.com',
    careerPage: 'https://adobe.wd5.myworkdayjobs.com/external_careers',
    aspectHint: 'horizontal',
    fallbackText: 'ADBE',
  },
  infosys: {
    id: 'infosys',
    slug: 'infosys',
    name: 'Infosys',
    logo: infosysLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['IT Consulting', 'Software Engineering', 'Cloud & DevOps', 'Data Analytics & Science'],
    description: 'Next-generation digital services and IT consulting company accelerating enterprise cloud & AI adoption.',
    website: 'https://www.infosys.com',
    careerPage: 'https://www.infosys.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'INFY',
  },
  accenture: {
    id: 'accenture',
    slug: 'accenture',
    name: 'Accenture',
    logo: accentureLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Management Consulting', 'IT Consulting', 'Strategy Advisory', 'Cloud & DevOps'],
    description: 'Global professional services firm providing strategy, consulting, digital transformation, and technology services.',
    website: 'https://www.accenture.com',
    careerPage: 'https://www.accenture.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'ACN',
  },
  tcs: {
    id: 'tcs',
    slug: 'tcs',
    name: 'Tata Consultancy Services',
    logo: tcsLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['IT Consulting', 'Software Engineering', 'Cloud & DevOps', 'Management Consulting'],
    description: 'Flagship IT services and business solutions organization part of the prestigious Tata Group.',
    website: 'https://www.tcs.com',
    careerPage: 'https://www.tcs.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'TCS',
  },
  deloitte: {
    id: 'deloitte',
    slug: 'deloitte',
    name: 'Deloitte',
    logo: deloitteLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Management Consulting', 'Tax & Audit Consulting', 'Risk Advisory', 'Financial Analysis'],
    description: 'Big Four professional services network offering audit, consulting, financial advisory, and risk management.',
    website: 'https://www2.deloitte.com',
    careerPage: 'https://www2.deloitte.com/careers.html',
    aspectHint: 'horizontal',
    fallbackText: 'D',
  },
  kpmg: {
    id: 'kpmg',
    slug: 'kpmg',
    name: 'KPMG',
    logo: kpmgLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Tax & Audit Consulting', 'Management Consulting', 'Financial Advisory', 'Risk Management'],
    description: 'Professional services firm specializing in audit, tax advisory, and business risk consulting.',
    website: 'https://home.kpmg',
    careerPage: 'https://home.kpmg/careers.html',
    aspectHint: 'horizontal',
    fallbackText: 'KPMG',
  },
  ey: {
    id: 'ey',
    slug: 'ey',
    name: 'EY (Ernst & Young)',
    logo: eyLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Tax & Audit Consulting', 'Strategy Advisory', 'Management Consulting', 'Risk Management'],
    description: 'Global leader in assurance, tax advisory, strategy consulting, and business transformation.',
    website: 'https://www.ey.com',
    careerPage: 'https://www.ey.com/careers',
    aspectHint: 'square',
    fallbackText: 'EY',
  },
  pwc: {
    id: 'pwc',
    slug: 'pwc',
    name: 'PwC (PricewaterhouseCoopers)',
    logo: pwcLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Tax & Audit Consulting', 'Management Consulting', 'Financial Analysis', 'Risk Advisory'],
    description: 'Big Four consulting network delivering quality in audit, assurance, and strategic business consulting.',
    website: 'https://www.pwc.com',
    careerPage: 'https://jobs.us.pwc.com',
    aspectHint: 'horizontal',
    fallbackText: 'PWC',
  },
  jpmorgan: {
    id: 'jpmorgan',
    slug: 'jpmorgan',
    name: 'JPMorgan Chase & Co.',
    logo: jpmorganLogo,
    industry: 'Banking, Finance & FinTech',
    industrySlug: 'finance',
    domains: ['Investment Banking', 'FinTech', 'Financial Analysis', 'Cybersecurity', 'Software Engineering'],
    description: 'Global financial services institution and investment bank pioneering trading tech and commercial banking.',
    website: 'https://www.jpmorganchase.com',
    careerPage: 'https://careers.jpmorgan.com',
    aspectHint: 'wide',
    fallbackText: 'JPM',
  },
  zscaler: {
    id: 'zscaler',
    slug: 'zscaler',
    name: 'Zscaler',
    logo: zscalerLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Cybersecurity', 'Cloud & DevOps', 'Software Engineering'],
    description: 'Cloud security leader pioneering the Zero Trust Exchange architecture for enterprise cybersecurity.',
    website: 'https://www.zscaler.com',
    careerPage: 'https://www.zscaler.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'ZS',
  },
  hsbc: {
    id: 'hsbc',
    slug: 'hsbc',
    name: 'HSBC',
    logo: hsbcLogo,
    industry: 'Banking, Finance & FinTech',
    industrySlug: 'finance',
    domains: ['Financial Analysis', 'Investment Banking', 'Risk Management', 'FinTech'],
    description: 'Global banking and financial services organization serving over 40 million commercial and personal clients.',
    website: 'https://www.hsbc.com',
    careerPage: 'https://www.hsbc.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'HSBC',
  },
  hdfc: {
    id: 'hdfc',
    slug: 'hdfc',
    name: 'HDFC Bank',
    logo: hdfcLogo,
    industry: 'Banking, Finance & FinTech',
    industrySlug: 'finance',
    domains: ['FinTech', 'Financial Analysis', 'Risk Management', 'Commercial Banking'],
    description: 'India’s premier private sector bank delivering digital banking, retail finance, and credit services.',
    website: 'https://www.hdfcbank.com',
    careerPage: 'https://www.hdfcbank.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'HDFC',
  },
  ibm: {
    id: 'ibm',
    slug: 'ibm',
    name: 'IBM',
    logo: ibmLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['AI / ML', 'Cloud & DevOps', 'Software Engineering', 'Data Analytics & Science'],
    description: 'Global innovation leader in hybrid cloud solutions, quantum computing, and enterprise AI (watsonx).',
    website: 'https://www.ibm.com',
    careerPage: 'https://www.ibm.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'IBM',
  },
  cisco: {
    id: 'cisco',
    slug: 'cisco',
    name: 'Cisco Systems',
    logo: ciscoLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Cybersecurity', '5G & Wireless Tech', 'Software Engineering', 'Cloud & DevOps'],
    description: 'Worldwide leader in networking hardware, telecommunications, security software, and IoT infrastructure.',
    website: 'https://www.cisco.com',
    careerPage: 'https://jobs.cisco.com',
    aspectHint: 'horizontal',
    fallbackText: 'CSCO',
  },
  concentrix: {
    id: 'concentrix',
    slug: 'concentrix',
    name: 'Concentrix',
    logo: concentrixLogo,
    industry: 'Consulting & Professional Services',
    industrySlug: 'consulting',
    domains: ['Management Consulting', 'Customer Experience', 'IT Consulting'],
    description: 'Global technology and customer experience leader delivering end-to-end digital business services.',
    website: 'https://www.concentrix.com',
    careerPage: 'https://jobs.concentrix.com',
    aspectHint: 'wide',
    fallbackText: 'CNXC',
  },

  // NEWLY INTEGRATED COMPANIES
  goldmansachs: {
    id: 'goldmansachs',
    slug: 'goldman-sachs',
    name: 'Goldman Sachs',
    logo: goldmanSachsLogo,
    industry: 'Banking, Finance & FinTech',
    industrySlug: 'finance',
    domains: ['Investment Banking', 'Quantitative Finance', 'Financial Analysis', 'FinTech'],
    description: 'Leading global investment banking, securities, and investment management firm.',
    website: 'https://www.goldmansachs.com',
    careerPage: 'https://www.goldmansachs.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'GS',
  },
  razorpay: {
    id: 'razorpay',
    slug: 'razorpay',
    name: 'Razorpay',
    logo: razorpayLogo,
    industry: 'Banking, Finance & FinTech',
    industrySlug: 'finance',
    domains: ['FinTech', 'Software Engineering', 'E-Commerce Platforms', 'Cybersecurity'],
    description: 'Leading payment gateway and full-stack financial technology platform for businesses.',
    website: 'https://razorpay.com',
    careerPage: 'https://razorpay.com/jobs',
    aspectHint: 'horizontal',
    fallbackText: 'RZP',
  },
  sunpharma: {
    id: 'sunpharma',
    slug: 'sun-pharma',
    name: 'Sun Pharma',
    logo: sunPharmaLogo,
    industry: 'Healthcare & Pharmaceuticals',
    industrySlug: 'healthcare',
    domains: ['Pharmaceutical Research', 'Biotechnology', 'Clinical Data Analysis'],
    description: 'Fourth largest global specialty generic pharmaceutical company operating across 100+ nations.',
    website: 'https://sunpharma.com',
    careerPage: 'https://sunpharma.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'SUN',
  },
  apollo: {
    id: 'apollo',
    slug: 'apollo-hospitals',
    name: 'Apollo Hospitals',
    logo: apolloLogo,
    industry: 'Healthcare & Pharmaceuticals',
    industrySlug: 'healthcare',
    domains: ['Healthcare Operations', 'Clinical Data Analysis', 'Health Informatics', 'Pharmaceutical Research'],
    description: 'Asia’s foremost integrated healthcare services provider operating super-specialty hospitals, pharmacies, and digital health platforms.',
    website: 'https://www.apollohospitals.com',
    careerPage: 'https://www.apollohospitals.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'APOLLO',
  },
  manipal: {
    id: 'manipal',
    slug: 'manipal-hospitals',
    name: 'Manipal Hospitals',
    logo: manipalLogo,
    industry: 'Healthcare & Pharmaceuticals',
    industrySlug: 'healthcare',
    domains: ['Healthcare Operations', 'Clinical Data Analysis', 'Biotechnology', 'Hospital Management'],
    description: 'Leading multi-specialty healthcare network providing tertiary and quaternary care, medical research, and health tech innovations.',
    website: 'https://www.manipalhospitals.com',
    careerPage: 'https://www.manipalhospitals.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'MANIPAL',
  },
  walmart: {
    id: 'walmart',
    slug: 'walmart-global-tech',
    name: 'Walmart Global Tech',
    logo: walmartLogo,
    industry: 'E-Commerce, Retail & FMCG',
    industrySlug: 'retail',
    domains: ['E-Commerce Platforms', 'Software Engineering', 'Supply Chain & Logistics', 'Data Analytics & Science'],
    description: 'Technology arm of Walmart powering e-commerce, automated fulfillment, and omni-channel retail tech.',
    website: 'https://www.walmart.com',
    careerPage: 'https://careers.walmart.com',
    aspectHint: 'horizontal',
    fallbackText: 'WMT',
  },
  hul: {
    id: 'hul',
    slug: 'hindustan-unilever',
    name: 'Hindustan Unilever',
    logo: hulLogo,
    industry: 'E-Commerce, Retail & FMCG',
    industrySlug: 'retail',
    domains: ['FMCG & Brand Marketing', 'Supply Chain & Logistics', 'Data Analytics & Science'],
    description: 'India’s largest consumer goods manufacturer providing iconic personal care, home, and refreshment brands.',
    website: 'https://www.hul.co.in',
    careerPage: 'https://www.hul.co.in/careers',
    aspectHint: 'square',
    fallbackText: 'HUL',
  },
  tatamotors: {
    id: 'tatamotors',
    slug: 'tata-motors',
    name: 'Tata Motors',
    logo: tataMotorsLogo,
    industry: 'Automotive & Industrial Manufacturing',
    industrySlug: 'automotive',
    domains: ['EV & Battery Tech', 'Embedded Systems', 'Industrial Automation'],
    description: 'Leading global automobile manufacturer pioneering electric mobility, commercial, and passenger vehicles.',
    website: 'https://www.tatamotors.com',
    careerPage: 'https://www.tatamotors.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'TATA',
  },
  jio: {
    id: 'jio',
    slug: 'reliance-jio-platforms',
    name: 'Reliance Jio Platforms',
    logo: jioLogo,
    industry: 'Telecommunications & Energy',
    industrySlug: 'telecom',
    domains: ['5G & Wireless Tech', 'Software Engineering', 'Cloud & DevOps', 'E-Commerce Platforms'],
    description: 'India’s largest digital services network driving 5G infrastructure, cloud services, and digital apps.',
    website: 'https://www.jio.com',
    careerPage: 'https://careers.jio.com',
    aspectHint: 'square',
    fallbackText: 'JIO',
  },
  delhivery: {
    id: 'delhivery',
    slug: 'delhivery',
    name: 'Delhivery',
    logo: delhiveryLogo,
    industry: 'Travel, Hospitality & Logistics',
    industrySlug: 'logistics',
    domains: ['Supply Chain & Logistics', 'Software Engineering', 'Data Analytics & Science'],
    description: 'India’s largest fully integrated logistics services provider offering automated express delivery.',
    website: 'https://www.delhivery.com',
    careerPage: 'https://www.delhivery.com/careers',
    aspectHint: 'horizontal',
    fallbackText: 'DLHV',
  },
  nvidia: {
    id: 'nvidia',
    slug: 'nvidia',
    name: 'NVIDIA',
    logo: nvidiaLogo,
    industry: 'Semiconductor & Hardware Tech',
    industrySlug: 'semiconductor',
    domains: ['AI / ML', 'VLSI & Semiconductor', 'Software Engineering', '3D Graphics & Animation'],
    description: 'Pioneer of GPU accelerated computing, generative AI hardware, CUDA software, and autonomous systems.',
    website: 'https://www.nvidia.com',
    careerPage: 'https://www.nvidia.com/en-us/about-nvidia/careers',
    aspectHint: 'horizontal',
    fallbackText: 'NVDA',
  },
  coursera: {
    id: 'coursera',
    slug: 'coursera',
    name: 'Coursera',
    logo: courseraLogo,
    industry: 'EdTech & Learning Solutions',
    industrySlug: 'edtech',
    domains: ['EdTech & Learning', 'Software Engineering', 'Data Analytics & Science'],
    description: 'Global online learning platform offering university degrees, professional certificates, and courses.',
    website: 'https://www.coursera.org',
    careerPage: 'https://about.coursera.org/careers',
    aspectHint: 'horizontal',
    fallbackText: 'COUR',
  },
  apple: {
    id: 'apple',
    slug: 'apple',
    name: 'Apple',
    logo: appleLogo,
    industry: 'Technology & Software',
    industrySlug: 'technology',
    domains: ['Software Engineering', 'Embedded Systems', 'UI/UX Design', 'AI / ML'],
    description: 'Global innovator creating iPhone, Mac, iPad, iOS, macOS, silicon chips, and digital services.',
    website: 'https://www.apple.com',
    careerPage: 'https://www.apple.com/careers',
    aspectHint: 'square',
    fallbackText: 'AAPL',
  },
};

// Aliases map for hyphenated & alternative company slugs to canonical keys
const ALIASES: Record<string, string> = {
  'goldman-sachs': 'goldmansachs',
  'goldmansachs': 'goldmansachs',
  'sun-pharma': 'sunpharma',
  'sunpharma': 'sunpharma',
  'apollo-hospitals': 'apollo',
  'apollo': 'apollo',
  'manipal-hospitals': 'manipal',
  'manipal': 'manipal',
  'walmart-global-tech': 'walmart',
  'walmart': 'walmart',
  'hindustan-unilever': 'hul',
  'hul': 'hul',
  'tata-motors': 'tatamotors',
  'tatamotors': 'tatamotors',
  'reliance-jio-platforms': 'jio',
  'jio': 'jio',
  'tcs': 'tcs',
  'tata-consultancy-services': 'tcs',
  'jpmorgan-chase': 'jpmorgan',
  'jpmorgan': 'jpmorgan',
  'hdfc-bank': 'hdfc',
  'hdfc': 'hdfc',
  'ey': 'ey',
  'ernst-young': 'ey',
  'pwc': 'pwc',
  'pricewaterhousecoopers': 'pwc',
};

// Build full export mapping supporting both canonical keys and aliases
export const COMPANY_CONFIGS: Record<string, CompanyConfig> = { ...BASE_COMPANY_CONFIGS };

Object.entries(ALIASES).forEach(([alias, targetKey]) => {
  if (BASE_COMPANY_CONFIGS[targetKey]) {
    COMPANY_CONFIGS[alias] = BASE_COMPANY_CONFIGS[targetKey];
  }
});

export const getCompanyConfig = (slugOrId?: string): CompanyConfig | undefined => {
  if (!slugOrId) return undefined;
  const raw = slugOrId.toLowerCase().replace(/^comp-/, '');
  const targetKey = ALIASES[raw] || raw;
  return COMPANY_CONFIGS[targetKey] || COMPANY_CONFIGS[raw];
};
